server:
  port: 8090
spring:
  #html,js等静态资源热部署
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources
  thymeleaf:
    cache: false
  #配置数据源
  datasource:
    druid:
      url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8}
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  #配置日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.xd.xdshiro.modules.sys.mapper
  mapper-locations: classpath:mapper/**/*.xml




shiro:
  anon:
    - /
  authc:
    - /add
    - /update